[versions]
agp = "8.1.1"
kotlin = "1.9.10"
kotlinter = "3.16.0"
xposed = "82"

[libraries]
xposed = { group = "de.robv.android.xposed", name = "api", version.ref = "xposed"}

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinter = { id = "org.jmailen.kotlinter", version.ref = "kotlinter" }
